### ISSUE TITLE
While parsing LW and SW instructions, offset cannot be negative or above 8192

### ISSUE THREAD

**Issue by OldWoman37** [lupino3/edumips64#175]
When parsing code with LW and SW, if the offset is negative or above 8192, you get an error that the label is too large. As far as I know, the instruction field is 16 bits which allows offsets from -32768 to 32767. There should also be a sign extension applied so that the arithmetic is correct for the 64 bit address path.
Also, you cannot use hexadecimal values for the labels either, it must be decimal.

**Comment by lupino3** [comment]
Hi, I expect to be able to have a look at this during this weekend. Thanks for the report!

**Comment by lupino3** [comment]
The limit of 8192 is there because it is hardcoded in `Memory.java`, see [link](https://github.com/lupino3/edumips64/blob/master/src/main/java/org/edumips64/core/Memory.java#L38). It is therefore not a problem in the parsing, but rather an hardcoded limitation.

Not sure if it's worth making it customizable in the UI, what do you think?

For negative numbers, that definitely seems to be a parsing problem, and I'll fix it.

**Comment by OldWoman37** [comment]
I'm certainly no Java expert, but from what I can see this limit is imposed on the index not the memory address. Since the memory addresses are divided by 8 to derive the index, I don't think this is the issue. The offset in MIPS is in bytes. In fact in an earlier version of EduMIPS I personally noted that the limit was no more than 512 (maybe version 1.2.0) so it must have been somewhat corrected from then.
Regardless, I don't think we can impose a limit on the offset since someone could write the code such that their pointer (R0-31) plus the offset could result in a small memory address which is well within the permissible range.

**Comment by lupino3** [comment]
(sorry for the delay!)

You are correct, the limit is imposed on the index, not on the memory address. But the bug here is that the code is comparing the offset value (in bytes) with the `DATALIMIT` (which is an index).

Fixing this now.

**Comment by lupino3** [comment]
Opened #206 to track the feature request about hexadecimal labels.
