### ISSUE TITLE
Migrate to Bazel

### ISSUE THREAD

**Issue by lupino3** [lupino3/edumips64#180]
Bazel (http://bazel.io) is a fast multi-platform build system which is easier to use than Gradle/Ant.

I am trying it out in the [bazel-migration](https://github.com/lupino3/edumips64/tree/bazel-migration) branch. If it can fully supersede Gradle+Ant, we should adopt it and get rid of Gradle and Ant.

**Comment by lupino3** [comment]
Getting proper build-time variables in the manifest depends on https://github.com/bazelbuild/bazel/issues/2009 being fixed.

**Comment by lupino3** [comment]
Missing features to consider the migration complete:
- [ ] build-time variables support (git revision, build timestamp)
- [ ] building the documentation
- [ ] adding Travis CI support to exercise the build
- [ ] building -nodeps JAR

Optional:
- [ ] adding support for building the Web UI with gwtc
- [ ] build CLI JAR

**Comment by pviotti** [comment]
@lupino3 please consider adopting a building system that is more commonly known and has better tooling support (IDEs, CI/CD, etc).  
I've set up the building configuration for Gradle in this branch: https://github.com/pviotti/edumips64/tree/gradle-build
It works pretty well, doesn't need Ant, and all the configuration needed so far is [gradle.build](https://github.com/pviotti/edumips64/blob/gradle-build/build.gradle).  
Currently missing feature (AFAIK):
 - [ ] Travis is failing on the latex to pdf task for some reason (but it works on my machine!;) 
 - [ ] git version stamping
 - [ ] splash screen support (?)
 - [ ] web ui support

**Comment by lupino3** [comment]
Hi Paolo, thanks for the bug reports and the initial code.

I like the work you did with Gradle: I think it's a better choice than Bazel at this point for a java-based desktop application like EduMIPS64.

Would you be willing to finalize the work on the Gradle build file and send a complete pull request to also remove Bazel at the same time?

Regarding the documentation: currently, the Travis build is working (https://travis-ci.org/lupino3/edumips64/builds/479339732), so the docs should build if everything is installed.

I think we should move the discussion to Issue #225, which you opened. Thanks!
