### ISSUE TITLE
Finish / improve  Gradle migration

### ISSUE THREAD

**Issue by pviotti** [lupino3/edumips64#228]
These are the remaining tasks to finish / improve the migration to Gradle (afaik):

- [ ] build / check scripts for GWT web ui, devmode (?)
- [x] update GH pages script and uncomment corresponding lines in .travis.yml (or remove them)
- [ ] minor: remove images and docs from cli jar
- [x] execute code coverage (to be uploaded to codecov.io)

**Comment by lupino3** [comment]
Note to self: this seems to be the most up-to-date gradle plugin for GWT: https://github.com/esoco/gwt-gradle-plugin

**Comment by lupino3** [comment]
@pviotti I started work on the GWT compilation, pushed it to the branch enable-gwt: https://github.com/lupino3/edumips64/tree/enable-gwt. It contains the initial configuration for the Gradle GWT plugin, and it seems to compile the code, but I haven't been able to get it to work end-to-end yet. Feel free to build on top of that, I don't think I'll be able to spend any time on it this weekend. Thanks!

**Comment by pviotti** [comment]
For the Web UI, there are alternatives to GWT that may be worth be considered. [Here](https://github.com/appcypher/awesome-wasm-langs#java) is the list. 
In particular, [TeaVM](http://teavm.org/) (with [its Gradle plugin](https://github.com/edibleday/teavm-gradle-plugin)) looks like a promising candidate.

**Comment by lupino3** [comment]
I agree that TeaVM looks promising, however I'd prefer to reuse the existing work to make GWT work.

I tried this plugin and it seems to be working: https://github.com/ascendtech/gwt-gradle. I'll get it to working in the simplest possible way and close the issue.
