### ISSUE TITLE
Register read semaphore never used

### ISSUE THREAD

**Issue by johnwu0604** [lupino3/edumips64#243]
I noticed that in the core/Register.java file, there are read and write semaphores that have been implemented for access control. 

While the write semaphore is used throughout the code base to enforce singular write access, I noticed the read semaphore methods (getReadSemaphore(), incrReadSemaphore(), decrReadSemaphore()) are never actually used anywhere. This means that technically there can be infinitely many reads of a Register during the same clock cycle.

Was this meant to be expected behaviour? Or were the read semaphores implemented and later decided that they weren't needed anymore?

**Comment by lupino3** [comment]
Hi John, thanks for the feedback. We had initially thought we would need read semaphores, so they were implemented while we were implementing write semaphores, but in the end we realized that they were not useful to model any type of data dependency. Therefore it is effectively dead code and could be removed, unless you have a suggestion on how to use them. Thanks!

**Comment by johnwu0604** [comment]
@lupino3 Okay thank you!

**Comment by lupino3** [comment]
No problem!
