### ISSUE TITLE
Add DMULU as an alias to DMULTU

### ISSUE THREAD

**Issue by 0mp** [lupino3/edumips64#249]
I'm testing a program which was tested on WinMIPS64 and features an instruction called `dmulu`.

When I start the program in EduMIPS64, however, I get an error that the code is invalid.

I've scanned through the repository and I cannot find out whether `dmulu` is missing from EduMIPS64 or if this is a bug.

Cheers & thank you for your work!

**Comment by 0mp** [comment]
It looks like `dmulu` is not mentioned at all in the documentation so it is not implemented.

**Comment by lupino3** [comment]
Hello, and thanks for your bug report!

Yes there is no `dmulu` instruction. I believe you want to use `dmultu` :)

Looking at the [MIPS64 ISA](https://scc.ustc.edu.cn/zlsc/lxwycj/200910/W020100308600769158777.pdf), there is no `dmulu` instruction there.

If there are many programs out there using it, I can add `dmulu` as an alias for `dmultu`.

Thanks,
Andrea

**Comment by 0mp** [comment]
I just happen to be working on an example MIPS program that is written with WinMIPS64 in mind (so maybe it uses some WinMIPS64-specific instructions). I wanted to use something that works natively on my FreeBSD box and I stumbled upon EduMIPS64.

I am not sure if this is sufficiently good reason to an alias.

PS EduMIPS64 is now available in the FreeBSD ports collection :) https://www.freshports.org/emulators/edumips64/

**Comment by lupino3** [comment]
Hey thanks a lot for adding EduMIPS64 in the ports collection! I will add the new instruction as soon as I can :)
