### ISSUE TITLE
Improve the bug window

### ISSUE THREAD

**Issue by lupino3** [lupino3/edumips64#256]
The report bug window does not contain all information necessary to reproduce a bug.

We need to add:
- [ ] the exact version of EduMIPS64 (git revision, build date)
- [ ] the full code of the program
- [ ] generic info about the operating system, JRE version

This will make the troubleshooting easier.

**Comment by lupino3** [comment]
- [ ] Similar text could also be added to the CLI if any exception gets bubbled up the stack and crashes the program.

**Comment by pviotti** [comment]
What do you mean by "full code of the program"? A link to its tag on GitHub..?
Anyway, I think I can tackle this one.

**Comment by lupino3** [comment]
I meant the code of the assembly file that is causing the problem. Thank
you!
