### ISSUE TITLE
Command Line Interface java.lang.NullPointerException

### ISSUE THREAD

**Issue by odxa20** [lupino3/edumips64#258]
I am getting this error when running from the CLI

Eseguo 1 step di simulazione
Eccezione durante lo step!!
java.lang.NullPointerException
        at org.edumips64.core.Dinero.IF(Dinero.java:61)
        at org.edumips64.core.is.ComputationalInstructions.IF(ComputationalInstructions.java:37)
        at org.edumips64.core.CPU.stepIF(CPU.java:654)
        at org.edumips64.core.CPU.step(CPU.java:405)
        at org.edumips64.MainCLI.main(MainCLI.java:151)

**Comment by lupino3** [comment]
Hi, thanks for reporting this bug. Could you please post the program you are running on the simulator and the full command line used to start the simulator? Thanks!

**Comment by odxa20** [comment]
I am running a modified version of the code (only change is DATALIMIT = 32768 instead of DATALIMIT = 8192) so that I can perform a 100*100 matrix multiplication. The program runs correctly in the graphical version but because it takes about 5 hours to complete execution and allocates more than 3GB of RAM I was trying to get the CLI version to work. I am attaching the program in this post
[naive.zip](https://github.com/lupino3/edumips64/files/4064094/naive.zip)

**Comment by odxa20** [comment]
Command used is java -jar edumips64-1.2.5-cli.jar -f naive.s

**Comment by lupino3** [comment]
Yeah, I think this is something similar to #255, I'll try to see why the CLI version fails with this program, and I will file a different issue to understand why the performance is so poor with a larger data size. I'll keep this for the CLI issue.

**Comment by odxa20** [comment]
Thank you very much. All help is appreciated. Do you think that fixing the CLI version might help performance or at least memory usage ? I also tested the CLI with another vey small program and it also failed. I am attaching said program too
[isort.zip](https://github.com/lupino3/edumips64/files/4064171/isort.zip)

**Comment by lupino3** [comment]
Memory usage should be smaller as there will be no GUI footprint, which is proportional to the number of cycles executed.

I'd have to look with a profiler to see what is the cause of the large memory usage, this seems weird. 3GB is a lot, but I don't remember what's the baseline memory consumption with no code.

For the CLI version, I am afraid it is not very well maintained, as people tend not to use it. It was born mostly as a testing version I used in the very early days, I have not spent time on it in a long time.

One way to see if it would work from the CLI would be to add your code as a unit test and run the tests.

I'll try to have a look this weekend, unfortunately I am pretty busy those days :/

**Comment by odxa20** [comment]
Ok thanks I will keep an eye here for any news. If I add my code as a unit test will I be able to get dinero output ?

**Comment by lupino3** [comment]
With a bit of effort, yes.

Look at how we do unit tests for trace files: https://github.com/lupino3/edumips64/blob/master/src/test/java/org/edumips64/EndToEndTests.java#L524

You can see how the `runTestAndCompareTracefileWithGolden` function gets the tracefile: https://github.com/lupino3/edumips64/blob/master/src/test/java/org/edumips64/EndToEndTests.java#L248

Probably if you remove the deletion of the temporary file here: https://github.com/lupino3/edumips64/blob/master/src/test/java/org/edumips64/EndToEndTests.java#L187 you should be able to retain the resulting trace file from the unit test.

Hope this helps!

**Comment by odxa20** [comment]
I hope I can get this working. It seems doable. Have a nice day and thanks for the replies
