### ISSUE TITLE
v1.2.6 compiled for Java 11

### ISSUE THREAD

**Issue by pviotti** [lupino3/edumips64#276]
(Congrats for the release! :)
Not sure this was intentional or if it's an issue at all, but I just wanted to point out that the released binaries were compiled for Java 11, so they're not executable in systems with older versions of the JRE (e.g. Ubuntu 16.04, which is an LTS still supported).  
You may want to release the binaries compiled for Java 8 instead, or make the dependency more explicit in the release notes and docs.

**Comment by lupino3** [comment]
Thanks Paolo, definitely not intentional! I should make the Java version explicit in the Gradle config.

**Comment by lupino3** [comment]
Fixed by uploading new JARs built with the updated Gradle build file. The version should be good now:

```
$ unzip edumips64-1.2.6.jar
$ javap -verbose org/edumips64/ui/swing/GUIIO.class | grep version
  minor version: 0
  major version: 52
```
