### ISSUE TITLE
The no-dependencies jar lacks images and docs

### ISSUE THREAD

**Issue by pviotti** [lupino3/edumips64#278]
While preparing the Arch Linux package for v1.2.6 I realized that `edumips64-1.2.6.jar` does not contain:  
- [ ] the `images` folder, which was present in `edumips64-1.2.5-nodeps.jar`, and whose absence makes the process crash upon startup
- [ ] the `docs` folder, which was not present in `edumips64-1.2.5-nodeps.jar` either, and whose absence prevent the user from loading the JavaHelp manual

**Comment by lupino3** [comment]
Woah. I guess I spot-checked the stand-alone version but not the no-deps JAR. Thanks for reporting this!

**Comment by lupino3** [comment]
Fixed by uploading a new JAR built with the fixed Gradle build file. Thanks!
