### ISSUE TITLE
Kate syntax highlighting

### ISSUE THREAD

**Issue by aleskandro** [lupino3/edumips64#59]
Hi, i'm a computer engineering student in Catania and we are using eduMips64 for a course. I edited the Mips Assembler syntax highlighting xml for Kate to have a better syntax highlighting for eduMips64. I don't know if there're all the calls registered.
I share it here so that you can push it somewhere if you want.
http://pastebin.com/tYt3S3TK

Bye

**Comment by lupino3** [comment]
Hi, thanks for your contribution!

If you want, you can send me a pull request, creating the "contrib" directory in the main tree and adding this file there, so that you can retain ownership of the commit itself. Otherwise, I can take care of doing it.

Andrea

**Comment by aleskandro** [comment]
Created the pull request using a fork in my account. I hope this is ok. As soon as possible I will push also the vim syntax highlighting. It is not a greater contribution but is a pleasure to contribute with the bit I can do falicitating my study.

**Comment by lupino3** [comment]
Thanks, the process was perfect and the pull request was accepted. All contributions are welcome, small or big :) If you want to improve something else and need some guidance on the code please let me know and I'll be more than happy to help!

**Comment by lupino3** [comment]
This was fixed by pull request #60.
