### ISSUE TITLE
Limited number of Labels

### ISSUE THREAD

**Issue by johnchronis** [lupino3/edumips64#64]
Hey,
does edumips have a limitation on the labels I can use per program? 
I think it only recognizes around 35 and the it gives me a parsing error.

**Comment by lupino3** [comment]
Hi,
no, there is no limitation on the number of labels. I just created a test program with 100 labels and it works fine.

Can you attach a source file that shows the bug? Maybe you have duplicate labels?

Thanks!

**Comment by johnchronis** [comment]
Hey, 
I am attaching a file with 50 labels. When I try to open it with edumips I get a parsing error that label below "label32" are not found (I have named the labels from label0 to label50).
I tried removing the first 2 labels and the error I am getting is that labels from label34 and below are not found. That's why I assumed there is an upper limit to the labels.

Thanks for your help,
John

**Comment by lupino3** [comment]
Thanks for the report. I could indeed reproduce the bug and will try to fix it.

**Comment by lupino3** [comment]
Hi, this issue was fixed. You were right, your code was hitting an internal limit `CPU.CODELIMIT`. To increase it, I had to do a few changes to the implementation, but now the limit is much higher.

I tested your code with the JAR built from the latest commit (http://lupino3.github.io/edumips64/edumips64-latest.jar), and it works.

Thanks for the but report!

**Comment by lupino3** [comment]
By the way, the parser now reports the "out of bounds" error. The code was there but a bug (fixed in commit 6d6adb) was stopping it from being triggered.

**Comment by johnchronis** [comment]
Thank you very much! 
I tested it and it works great!

**Comment by lupino3** [comment]
Cool, thanks for the bug report!

The fix will be in the next release.
